package com.itcast.tpms.model;

import java.util.Date;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.credit
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    private Float credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.class_hour
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    private Integer classHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.type
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher_id
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    private Long teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.gmt_created
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.gmt_modified
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.english_name
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    private String englishName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_quality
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    private Integer courseQuality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.module_id
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    private Long moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.assessment_method
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    private Integer assessmentMethod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.credit
     *
     * @return the value of course.credit
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public Float getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.credit
     *
     * @param credit the value for course.credit
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public void setCredit(Float credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.class_hour
     *
     * @return the value of course.class_hour
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public Integer getClassHour() {
        return classHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.class_hour
     *
     * @param classHour the value for course.class_hour
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public void setClassHour(Integer classHour) {
        this.classHour = classHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.type
     *
     * @return the value of course.type
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.type
     *
     * @param type the value for course.type
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher_id
     *
     * @return the value of course.teacher_id
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher_id
     *
     * @param teacherId the value for course.teacher_id
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.gmt_created
     *
     * @return the value of course.gmt_created
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.gmt_created
     *
     * @param gmtCreated the value for course.gmt_created
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.gmt_modified
     *
     * @return the value of course.gmt_modified
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.gmt_modified
     *
     * @param gmtModified the value for course.gmt_modified
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.english_name
     *
     * @return the value of course.english_name
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.english_name
     *
     * @param englishName the value for course.english_name
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_quality
     *
     * @return the value of course.course_quality
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public Integer getCourseQuality() {
        return courseQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_quality
     *
     * @param courseQuality the value for course.course_quality
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public void setCourseQuality(Integer courseQuality) {
        this.courseQuality = courseQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.module_id
     *
     * @return the value of course.module_id
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public Long getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.module_id
     *
     * @param moduleId the value for course.module_id
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.assessment_method
     *
     * @return the value of course.assessment_method
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public Integer getAssessmentMethod() {
        return assessmentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.assessment_method
     *
     * @param assessmentMethod the value for course.assessment_method
     *
     * @mbg.generated Mon Mar 09 20:21:53 CST 2020
     */
    public void setAssessmentMethod(Integer assessmentMethod) {
        this.assessmentMethod = assessmentMethod;
    }
}