package com.itcast.tpms.model;

import java.util.Date;

public class Curriculum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.id
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.name
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.current
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private Integer current;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.grade
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.need_obligatory_class_hour
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private Integer needObligatoryClassHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.need_obligatory_credit
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private Integer needObligatoryCredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.need_elective_class_hour
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private Integer needElectiveClassHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.need_elective_credit
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private Integer needElectiveCredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.major_id
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private Long majorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.gmt_created
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.gmt_modified
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.id
     *
     * @return the value of curriculum.id
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.id
     *
     * @param id the value for curriculum.id
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.name
     *
     * @return the value of curriculum.name
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.name
     *
     * @param name the value for curriculum.name
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.current
     *
     * @return the value of curriculum.current
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public Integer getCurrent() {
        return current;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.current
     *
     * @param current the value for curriculum.current
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setCurrent(Integer current) {
        this.current = current;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.grade
     *
     * @return the value of curriculum.grade
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.grade
     *
     * @param grade the value for curriculum.grade
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.need_obligatory_class_hour
     *
     * @return the value of curriculum.need_obligatory_class_hour
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public Integer getNeedObligatoryClassHour() {
        return needObligatoryClassHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.need_obligatory_class_hour
     *
     * @param needObligatoryClassHour the value for curriculum.need_obligatory_class_hour
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setNeedObligatoryClassHour(Integer needObligatoryClassHour) {
        this.needObligatoryClassHour = needObligatoryClassHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.need_obligatory_credit
     *
     * @return the value of curriculum.need_obligatory_credit
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public Integer getNeedObligatoryCredit() {
        return needObligatoryCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.need_obligatory_credit
     *
     * @param needObligatoryCredit the value for curriculum.need_obligatory_credit
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setNeedObligatoryCredit(Integer needObligatoryCredit) {
        this.needObligatoryCredit = needObligatoryCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.need_elective_class_hour
     *
     * @return the value of curriculum.need_elective_class_hour
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public Integer getNeedElectiveClassHour() {
        return needElectiveClassHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.need_elective_class_hour
     *
     * @param needElectiveClassHour the value for curriculum.need_elective_class_hour
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setNeedElectiveClassHour(Integer needElectiveClassHour) {
        this.needElectiveClassHour = needElectiveClassHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.need_elective_credit
     *
     * @return the value of curriculum.need_elective_credit
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public Integer getNeedElectiveCredit() {
        return needElectiveCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.need_elective_credit
     *
     * @param needElectiveCredit the value for curriculum.need_elective_credit
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setNeedElectiveCredit(Integer needElectiveCredit) {
        this.needElectiveCredit = needElectiveCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.major_id
     *
     * @return the value of curriculum.major_id
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public Long getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.major_id
     *
     * @param majorId the value for curriculum.major_id
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setMajorId(Long majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.gmt_created
     *
     * @return the value of curriculum.gmt_created
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.gmt_created
     *
     * @param gmtCreated the value for curriculum.gmt_created
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.gmt_modified
     *
     * @return the value of curriculum.gmt_modified
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.gmt_modified
     *
     * @param gmtModified the value for curriculum.gmt_modified
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}