package com.itcast.tpms.model;

import java.util.Date;

public class Major {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.id
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.name
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.gmt_created
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.gmt_modified
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.id
     *
     * @return the value of major.id
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.id
     *
     * @param id the value for major.id
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.name
     *
     * @return the value of major.name
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.name
     *
     * @param name the value for major.name
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.gmt_created
     *
     * @return the value of major.gmt_created
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.gmt_created
     *
     * @param gmtCreated the value for major.gmt_created
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.gmt_modified
     *
     * @return the value of major.gmt_modified
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.gmt_modified
     *
     * @param gmtModified the value for major.gmt_modified
     *
     * @mbg.generated Wed Feb 19 15:45:36 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}