package com.itcast.tpms.model;

import java.util.Date;

public class Module {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.id
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.name
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.pre_level_id
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    private Long preLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.gmt_created
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.gmt_modified
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.rank
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    private Integer rank;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.id
     *
     * @return the value of module.id
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.id
     *
     * @param id the value for module.id
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.name
     *
     * @return the value of module.name
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.name
     *
     * @param name the value for module.name
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.pre_level_id
     *
     * @return the value of module.pre_level_id
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    public Long getPreLevelId() {
        return preLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.pre_level_id
     *
     * @param preLevelId the value for module.pre_level_id
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    public void setPreLevelId(Long preLevelId) {
        this.preLevelId = preLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.gmt_created
     *
     * @return the value of module.gmt_created
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.gmt_created
     *
     * @param gmtCreated the value for module.gmt_created
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.gmt_modified
     *
     * @return the value of module.gmt_modified
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.gmt_modified
     *
     * @param gmtModified the value for module.gmt_modified
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.rank
     *
     * @return the value of module.rank
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.rank
     *
     * @param rank the value for module.rank
     *
     * @mbg.generated Fri Feb 28 16:16:39 CST 2020
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }
}