package com.itcast.tpms.mapper;

import com.itcast.tpms.model.CurriculumMidCourse;
import com.itcast.tpms.model.CurriculumMidCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CurriculumMidCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_mid_course
     *
     * @mbg.generated Tue Feb 18 20:14:35 CST 2020
     */
    long countByExample(CurriculumMidCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_mid_course
     *
     * @mbg.generated Tue Feb 18 20:14:35 CST 2020
     */
    int deleteByExample(CurriculumMidCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_mid_course
     *
     * @mbg.generated Tue Feb 18 20:14:35 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_mid_course
     *
     * @mbg.generated Tue Feb 18 20:14:35 CST 2020
     */
    int insert(CurriculumMidCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_mid_course
     *
     * @mbg.generated Tue Feb 18 20:14:35 CST 2020
     */
    int insertSelective(CurriculumMidCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_mid_course
     *
     * @mbg.generated Tue Feb 18 20:14:35 CST 2020
     */
    List<CurriculumMidCourse> selectByExampleWithRowbounds(CurriculumMidCourseExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_mid_course
     *
     * @mbg.generated Tue Feb 18 20:14:35 CST 2020
     */
    List<CurriculumMidCourse> selectByExample(CurriculumMidCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_mid_course
     *
     * @mbg.generated Tue Feb 18 20:14:35 CST 2020
     */
    CurriculumMidCourse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_mid_course
     *
     * @mbg.generated Tue Feb 18 20:14:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") CurriculumMidCourse record, @Param("example") CurriculumMidCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_mid_course
     *
     * @mbg.generated Tue Feb 18 20:14:35 CST 2020
     */
    int updateByExample(@Param("record") CurriculumMidCourse record, @Param("example") CurriculumMidCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_mid_course
     *
     * @mbg.generated Tue Feb 18 20:14:35 CST 2020
     */
    int updateByPrimaryKeySelective(CurriculumMidCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_mid_course
     *
     * @mbg.generated Tue Feb 18 20:14:35 CST 2020
     */
    int updateByPrimaryKey(CurriculumMidCourse record);
}